// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Notification struct {
	ID        int32
	UserID    int32
	Message   string
	CreatedAt pgtype.Timestamp
}

type Todo struct {
	ID        int32
	UserID    int32
	Name      pgtype.Text
	CreatedAt pgtype.Timestamp
}

type TodoItem struct {
	ID        int32
	TodoID    int32
	Content   string
	Urgency   interface{}
	Done      bool
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID           int32
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
}
