// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Notification struct {
	ID        int32
	UserID    int32
	Message   string
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID        int32
	Username  string
	Email     string
	CreatedAt pgtype.Timestamp
}
