// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package database

import (
	"context"
)

const getUserNotifications = `-- name: GetUserNotifications :many
SELECT id, user_id, message, created_at FROM notifications WHERE user_id = $1
`

func (q *Queries) GetUserNotifications(ctx context.Context, userID int32) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getUserNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
